### ISSUE TITLE
Invalid docker reference in demo/Docker/createDockerCluster.sh

### ISSUE THREAD

**Issue by JefJansen79** [ibm-messaging/mq-uniform-clusters#9]
The image in the docker run command contains two times the version tag. 

For example line 57-66
docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --env MQ_ENABLE_METRICS=true \
  --volume qm1UCdata:/mnt/mqm \
  --volume $scriptDir/QMConfig/dockerVolume/AutoCluster.ini:/etc/mqm/AutoCluster.ini \
  --volume $scriptDir/QMConfig/dockerVolume/UniCluster.mqsc:/etc/mqm/UniCluster.mqsc \
  --publish 1411:1414 --publish 9441:9443 \
  --network mqnetwork --network-alias QM1 \
  --detach --name QM1 **icr.io/ibm-messaging/mq:latest:latest**

**Comment by dware30** [comment]
Thanks for spotting this. Fixed
